development:
  cloud_name: duuqqcc3z
  api_key: '532833937664143'
  api_secret: qOya1hTJ8VMdeef-Newp4XbPCzU
  enhance_image_tag: true
  static_image_support: false

# production:
#   cloud_name: duuqqcc3z
#   api_key: <%= ENV["CLOUDINARY_API_KEY"] %>
#   api_secret: <%= ENV["CLOUDINARY_API_SECRET"] %>
#   enhance_image_tag: true
#   static_image_support: true
# test:
#   cloud_name: duuqqcc3z
#   api_key: '532833937664143'
#   api_secret: qOya1hTJ8VMdeef-Newp4XbPCzU
#   enhance_image_tag: true
#   static_image_support: false
